name: "[ACTION] Daily Release"
description: "A composite action to handle daily releases"
# https://github.com/godners/Shared_Actions/daily-release/action.yml

inputs:
  GITHUB_TOKEN:
    description: "The GitHub Token from the calling repository"
    retuired: true
    
outputs:
  has_changes:
    description: "Whether there are new changes to release"
    value: ${{ steps.daily-release.outputs.has_changes }}
  release_tag:
    description: "The tag generated for the release"
    value: ${{ steps.daily-release.outputs.release_tag }}

runs:
  using: "composite"
  steps:
    - name: "[STEP] Validate Token Inputed via Command"
      id: Validate
      shell: bash
      run: |
        if [ -z "${{ inputs.GITHUB_TOKEN }}" ]
        then
          TIME="$(date '+%F %T') (UTC)"
          TITLE="Daily Release"
          MESSAGE="GITHUB_TOKEN is missing or empty. Workflow terminated."
          SUMMARY="[${TITLE} ${TIME}: ${MESSAGE}]"
          echo "${SUMMARY}" >> $GITHUB_STEP_SUMMARY
          echo "${SUMMARY}"
          echo "summary=${SUMMARY}" >> $GITHUB_OUTPUT
          exit 1
        fi

    - name: "[STEP] Run Checkout Repository via Action"
      id: Checkout
      uses: actions/checkout@main
      with:
        fetch-depth: 0
        token: ${{ inputs.GITHUB_TOKEN }}
        
    - name: "[STEP] Run Worker (Check) via Command"
      id: Worker-Check
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
        GH_TOKEN: ${{ inputs.GITHUB_TOKEN }}
      run:
        LATEST_TAG=$(gh release list --limit 1 --json tagName -jq '.[0].tagName' 2>/dev/null || echo "")
        if [ -z "$LATEST_TAG" ]
        then
          echo "has_changes=true" >> $GITHUB_OUTPUT
          exit 0
        fi
        LASTEST_SHA=$(git rev-parse "$LATEST_TAG^{commit}" 2>/dev/null || echo "")
        CURRENT_SHA=$(git rev-parse HEAD)
        if [ "$LASTEST_SHA" = "$CURRENT_SHA" ] 
        then
          echo "has_changes=false" >> $GITHUB_OUTPUT
        else
          echo "has_changes=true"  >> $GITHUB_OUTPUT
        fi
    
    - name: "[STEP] Print Summary (NO Changes) via Command"
      id: Summary-NoChanges
      if: steps.Worker-Check.outputs.has_changes == 'false'
      shell: bash
      run: |
        TIME="$(date '+%F %T') (UTC)"
        TITLE="Daily Release"
        MESSAGE="Relasee canceled because No Changes"
        SUMMARY="[${TITLE} ${TIME}: ${MESSAGE}]"
        echo "${SUMMARY}" >> $GITHUB_STEP_SUMMARY
        echo "${SUMMARY}"
        echo "summary=${SUMMARY}" >> $GITHUB_OUTPUT
    
    - name: "[STEP] Run Worker (Info) via COmmand"
      id: Worker-Info
      if: steps.Worker-Check.outputs.has_changes == 'true'
      shell: bash
      run: |
        TODAY=$(date '+%Y.%m.%d')
        TAG="${TODAY}.auto"
        echo "tag=${TAG}" >> $GITHUB_OUTPUT
        TIME="$(date '+%F %T') (UTC)"
        echo "time=${TIME}" >> $GITHUB_OUTPUT

    - name: "[STEP] Remove Existent Release via Command"
      id: Remove
      if: steps.Worker-Check.outputs.has_changes == 'true'
      shell: bash
      env:
        GH_TOKEN ${{ inputs.GITHUB_TOKEN }}
      run: gh release delete ${{ steps.Worker-Info.outputs.tag }} --yes --cleanup-tag 2>/dev/null || echo ""
      
    - name: "[STEP] Create New Release via Action"
      id: Create
      if: steps.Worker-Check.outputs.has_changes == 'true'
      uses: softprops/action-gh-release@master
      env:
        GITHUB_OUTPUT: ${{ inputs.GITHUB_OUTPUT }}
      with:
        tag_name: ${{ steps.Worker-Info.outputs.tag }}
        name: ${{ steps.Worker-Info.outputs.tag }}
        body: |
          - TAG: ${{ steps.Worker-Info.outputs.tag }}
          - TIME: ${{ steps.Worker-Info.outputs.time }}
          - NOTE: This Release Created by Workflow [Daily-Release]
          - URL: <https://github.com/godners/Shared_Actions/daily-release/action.yml>
        draft: false
        prerelease: false

    - name: "[STEP] Print Summary (Has Changes) via Command"
      id: Summary-has_changes
      if: steps.Worker-Check.outputs.has_changes == 'true'
      shell: bash
      run: |
        TIME="$(date '+%F %T') (UTC)"
        TITLE="Daily Release"
        MESSAGE="Tag is <${{ steps.Worker-Info.outputs.tag }}>, Time is <${{ steps.Worker-Info.outputs.time }}>."
        SUMMARY="[${TITLE} ${TIME}: ${MESSAGE}]"
        echo "${SUMMARY}" >> $GITHUB_STEP_SUMMARY
        echo "${SUMMARY}"
        echo "summary=${SUMMARY}" >> $GITHUB_OUTPUT


