name: "[WORKFLOW] Daily Release"
# .github/workflows/daily-release.yml

on:
  schedule:
    - cron: '00 16 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  daily-release:
    runs-on: ubuntu-latest   # self-hosted
    steps:
      - uses: godners/Shared_Actions/daily-release@main
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
