name: "[WORKFLOW] Periodic Release"
# .github/workflows/periodic-release.yml

on:
  schedule:
    - cron: '00 16 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  daily-release:
    runs-on: ubuntu-latest   # self-hosted
    steps:
      - uses: ./periodic-release
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
